joint_limits:
  r_shoulder_pan_joint:
    has_velocity_limits: true
#     max_velocity: 1.0
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 1.0
    max_acceleration: 0.1
  r_shoulder_lift_joint:
    has_velocity_limits: true
#     max_velocity: 1.0
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 1.0
    max_acceleration: 0.1
  r_upper_arm_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
  r_elbow_flex_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
  r_forearm_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 5.0
    max_acceleration: 0.1
  r_wrist_flex_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 5.0
    max_acceleration: 0.1
  r_wrist_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.123352
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 5.0
    max_acceleration: 0.1
  l_shoulder_pan_joint:
    has_velocity_limits: true
#     max_velocity: 1.0
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 1.0
    max_acceleration: 0.1
  l_shoulder_lift_joint:
    has_velocity_limits: true
#     max_velocity: 1.0
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 1.0
    max_acceleration: 0.1
  l_upper_arm_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
  l_elbow_flex_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
  l_forearm_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
    angle_wraparound: true
  l_wrist_flex_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
  l_wrist_roll_joint:
    has_velocity_limits: true
#     max_velocity: 1.5
    max_velocity: 0.2
    has_acceleration_limits: true
#     max_acceleration: 2.0
    max_acceleration: 0.1
