sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /tilt_scan_filtered
    point_cloud_topic: /kinect_throttled
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    filtered_cloud_topic: self_filtered_cloud
