footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.59
footprint_padding: 0.015
oscillation_timeout: 20.0    # NOTE oscillation_timeout includes the global planner's planning time in vanila move_base.. use a fixed version!
oscillation_distance: 0.5
