PoseFollower3D:
  k_trans: 1.5
  k_rot: 1.25
  max_vel_lin: 0.4
  min_vel_lin: 0.05
  max_vel_th: 0.4
  min_vel_th: 0.10
  min_in_place_vel_th: 0.3
  in_place_trans_vel: 0.01

  tolerance_trans: 0.2 # 0.02
  tolerance_rot: 0.2
  tolerance_timeout: 0.5

  samples: 4 # for downscaling of traj. in the local planner when there is a collision

  trans_stopped_velocity: 0.005 # if odom reading is slower than this, then robot is stopped
  rot_stopped_velocity: 0.005 # if odom reading is slower than this, then robot is stopped

  transform_tolerance: 0.2

  # for forward simulation to check collisions of local plan:
  sim_time: 1.0
  sim_granularity: 0.2

  holonomic_robot: true


SBPLLatticePlanner3D:
  environment_type: XYThetaLattice
  planner_type: ARAPlanner
  allocated_time: 30.0
  initial_epsilon: 1.0
  forward_search: false

